// <auto-generated />
using System;
using GymAPI.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymAPI.Infrastructure.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260713234208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymAPI.Infrastructure.Persistence.Entities.ExerciseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("GymAPI.Infrastructure.Persistence.Entities.ExerciseEquipmentEntity", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.HasKey("ExerciseId", "EquipmentType");

                    b.ToTable("ExerciseEquipments");
                });

            modelBuilder.Entity("GymAPI.Infrastructure.Persistence.Entities.ExerciseMuscleGroupEntity", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer");

                    b.HasKey("ExerciseId", "MuscleGroup");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("GymAPI.Infrastructure.Persistence.Entities.ExerciseEquipmentEntity", b =>
                {
                    b.HasOne("GymAPI.Infrastructure.Persistence.Entities.ExerciseEntity", "Exercise")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GymAPI.Infrastructure.Persistence.Entities.ExerciseMuscleGroupEntity", b =>
                {
                    b.HasOne("GymAPI.Infrastructure.Persistence.Entities.ExerciseEntity", "Exercise")
                        .WithMany("ExerciseMuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GymAPI.Infrastructure.Persistence.Entities.ExerciseEntity", b =>
                {
                    b.Navigation("ExerciseEquipments");

                    b.Navigation("ExerciseMuscleGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
